base_url = "https://rawsp33d.github.io/oi"
title = "Oi"
description = "Your friendly neighborhood programming language."

theme = "zap"
# theme = "adidoks"
# theme = "book"
# theme = "terminimal"

compile_sass = true
build_search_index = true

[markdown]

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"
theme = "github-dark"

[extra]

keywords = "oi, language, programming-language, compiler"

menu_links = [
	{ name = "/", url = "/" },
	{ name = "/features", url = "/features" },
	{ name = "/about", url = "/about" },
	{ name = "/docs", url = "/docs/oi" },
	{ name = "source", url = "https://github.com/rawsp33d/oi" },
]

# zap
mode = "product"
github = "https://github.com/rawsp33d/oi"
