name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    # TODO: doctests
    steps:
    - uses: actions/checkout@v7

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt

    - name: rust:build
      run: cargo build --verbose

    - name: rust:clippy
      run: cargo clippy --all -- -D warnings

    - name: rust:tests
      run: cargo test --verbose
