name: docs

on:
  push:
    branches: [ main ]
    paths:
      - "**"
      - "!.github/**.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "**"
      - "!.github/**.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: rust:build
        run: cargo build --verbose

      - uses: Swatinem/rust-cache@v2

      - name: rust:docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"

      - name: fix:docs
        run: |
          mkdir -p ./www/static/
          rm -rf ./www/static/docs
          mv ./target/doc/ ./www/static/docs/

      - uses: getzola/github-pages@v1
        id: docs
        with:
          zola_version: v0.22.1
          working_directory: "www"
          build_flags: "--base-url {{ steps.docs.outputs.page_url }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.docs.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v5
        id: docs
